### ISSUE TITLE
M-ADA

### ISSUE THREAD

**Issue by scabcd1234** [ExplainableML/ACVC#3]
Hello, thank you for your contribution to the Single Source Domain Generalization Institute. I have a question want to ask you, you can compare the precision of the method of M - ADA is how to get, I'm not found in the code for the implementation of this method.

**Comment by cuguilke** [comment]
Hi @scabcd1234, we did not compare with M-ADA, but we did compared with ME-ADA, and for that I modified the original implementation and ran on our benchmark. Here is the link: https://github.com/garyzhao/ME-ADA

**Comment by scabcd1234** [comment]
Ok,tanks
